name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Install Jazzy
      run: gem install jazzy
    - name: Run Jazzy
      run: jazzy --min-acl internal
    - name: Upload Doc
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: docs/
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
